version: "3"
services:
   app:
     build:
       args:
         user: javier
         uid: 1000
       context: ./
       dockerfile: Dockerfile
     image: casaruraldb
     container_name: casaruraldb-app
     restart: unless-stopped
     working_dir: /var/www/
     volumes:
       - ./:/var/www
     networks:
       - net-casaruraldb
   db:
     image: mysql:5.7
     container_name: casaruraldb-db
     restart: unless-stopped
     ports:
      - 127.0.0.1:23306:3306
     environment:
       MYSQL_DATABASE: ${DB_DATABASE}
       MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
       MYSQL_PASSWORD: ${DB_PASSWORD}
       MYSQL_USER: ${DB_USERNAME}
       SERVICE_TAGS: dev
       SERVICE_NAME: mysql
     volumes:
       - ./docker-compose/mysql:/docker-entrypoint-initdb.d
       - ../casaruraldb-db/var/lib/mysql:/var/lib/mysql
     networks:
       - net-casaruraldb
   nginx:
         image: nginx:alpine
         container_name: casaruraldb-nginx
         restart: unless-stopped
         ports:
           - 127.0.0.1:28000:80
         volumes:
           - ./:/var/www
           - ./docker-compose/nginx:/etc/nginx/conf.d/
         networks:
           - net-casaruraldb
networks:
   net-casaruraldb:
     driver: bridge